export const datos = [
  {
    idCelular: "CEL_0001",
    marca: "Apple",
    modelo: "iPhone 11",
    precio: "$699",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/6n3FBS7/image.png",
  },
  {
    idCelular: "CEL_0002",
    marca: "Apple",
    modelo: "iPhone 11 Pro Max",
    precio: "$1099",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/smkq4bC/image.png",
  },
  {
    idCelular: "CEL_0003",
    marca: "Apple",
    modelo: "iPhone 12",
    precio: "$799",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/Dkc88zR/image.png",
  },
  {
    idCelular: "CEL_0004",
    marca: "Apple",
    modelo: "iPhone 12 mini",
    precio: "$699",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/4gn9j7b/image.png",
  },
  {
    idCelular: "CEL_0005",
    marca: "Apple",
    modelo: "iPhone 12 Pro",
    precio: "$999",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/FgX9x0G/image.png",
  },
  {
    idCelular: "CEL_0006",
    marca: "Apple",
    modelo: "iPhone 12 Pro Max",
    precio: "$1099",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/cDKTynP/image.png",
  },
  {
    idCelular: "CEL_0007",
    marca: "Apple",
    modelo: "iPhone 13",
    precio: "$799",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/LSpkTHr/image.png",
  },
  {
    idCelular: "CEL_0008",
    marca: "Apple",
    modelo: "iPhone 13 mini",
    precio: "$699",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/LSpkTHr/image.png",
  },
  {
    idCelular: "CEL_0009",
    marca: "Apple",
    modelo: "iPhone 13 Pro",
    precio: "$999",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/NpYLcvN/image.png",
  },
  {
    idCelular: "CEL_0010",
    marca: "Apple",
    modelo: "iPhone 13 Pro Max",
    precio: "$1099",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/NpYLcvN/image.png",
  },
  {
    idCelular: "CEL_0019",
    marca: "Asus",
    modelo: "ROG Phone 2",
    precio: "$899",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/K6wTyZH/image.png",
  },
  {
    idCelular: "CEL_0020",
    marca: "Asus",
    modelo: "ROG Phone 3",
    precio: "$999",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/0DvRRXf/image.png",
  },
  {
    idCelular: "CEL_0021",
    marca: "Asus",
    modelo: "ROG Phone 5",
    precio: "$799",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/478gPwv/image.png",
  },
  {
    idCelular: "CEL_0022",
    marca: "Asus",
    modelo: "Smartphone for Snapdragon Insiders",
    precio: "$1499",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/BrJMz5n/image.png",
  },
  {
    idCelular: "CEL_0023",
    marca: "Asus",
    modelo: "ZenFone 5",
    precio: "$399",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/yS5T1Jn/image.png",
  },
  {
    idCelular: "CEL_0024",
    marca: "Asus",
    modelo: "ZenFone 6",
    precio: "$499",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/w6T4LLB/image.png",
  },
  {
    idCelular: "CEL_0025",
    marca: "Asus",
    modelo: "ZenFone 7 Pro",
    precio: "$799",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/gDmd88s/image.png",
  },
  {
    idCelular: "CEL_0026",
    marca: "Asus",
    modelo: "Zenfone 8",
    precio: "$629",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/7z3mG6W/image.png",
  },
  {
    idCelular: "CEL_0027",
    marca: "Asus",
    modelo: "Zenfone 8 Flip",
    precio: "$799",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/dcfkdTn/image.png",
  },
  {
    idCelular: "CEL_0033",
    marca: "Google",
    modelo: "Pixel 4",
    precio: "$799",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/St4yTDC/kindpng-1091525.png",
  },
  {
    idCelular: "CEL_0034",
    marca: "Google",
    modelo: "Pixel 4a",
    precio: "$349",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/Qdpx5Rx/image.png",
  },
  {
    idCelular: "CEL_0035",
    marca: "Google",
    modelo: "Pixel 5",
    precio: "$699",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/FYRDkCJ/image.png",
  },
  {
    idCelular: "CEL_0036",
    marca: "Google",
    modelo: "Pixel 6",
    precio: "$599",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/SQYNNPw/image.png",
  },
  {
    idCelular: "CEL_0037",
    marca: "Google",
    modelo: "Pixel 6 Pro",
    precio: "$899",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/b3nNy76/image.png",
  },
  {
    idCelular: "CEL_0038",
    marca: "Huawei",
    modelo: "Mate 20 Pro",
    precio: "$999",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/b3nNy76/image.png",
  },
  {
    idCelular: "CEL_0039",
    marca: "Huawei",
    modelo: "Mate 20 X",
    precio: "$899",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/b3nNy76/image.png",
  },
  {
    idCelular: "CEL_0042",
    marca: "Huawei",
    modelo: "Mate 40 Pro",
    precio: "$1199",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/W2ZH8Mq/image.png",
  },
  {
    idCelular: "CEL_0043",
    marca: "Huawei",
    modelo: "Mate 40 Pro+",
    precio: "$1363",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/5KXdwTZ/image.png",
  },
  {
    idCelular: "CEL_0044",
    marca: "Huawei",
    modelo: "nova 6 5G",
    precio: "$576",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/sCY2wzv/image.png",
  },
  {
    idCelular: "CEL_0047",
    marca: "Huawei",
    modelo: "P40",
    precio: "$799",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/Vv9pnng/image.png",
  },
  {
    idCelular: "CEL_0048",
    marca: "Huawei",
    modelo: "P40 Lite",
    precio: "$279",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/7gJYm2g/image.png",
  },
  {
    idCelular: "CEL_0049",
    marca: "Huawei",
    modelo: "P40 Pro",
    precio: "$1099",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/m6ZrxTh/image.png",
  },
  {
    idCelular: "CEL_0050",
    marca: "Huawei",
    modelo: "P50 Pro",
    precio: "$907",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/mSSR6v7/image.png",
  },
  {
    idCelular: "CEL_0051",
    marca: "Lenovo",
    modelo: "Legion Phone 2 Pro",
    precio: "$799",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/Fh3fzNX/image.png",
  },
  {
    idCelular: "CEL_0052",
    marca: "Lenovo",
    modelo: "Legion Phone Pro",
    precio: "$899",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/nR0ftVc/image.png",
  },
  {
    idCelular: "CEL_0053",
    marca: "Lenovo",
    modelo: "Z6 Pro",
    precio: "$499",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/xqWdXFx/image.png",
  },
  {
    idCelular: "CEL_0055",
    marca: "LG",
    modelo: "G8 ThinQ",
    precio: "$819",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/BVsr0Pg/image.png",
  },
  {
    idCelular: "CEL_0057",
    marca: "LG",
    modelo: "V40 ThinQ",
    precio: "$899",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/qk27T6Z/image.png",
  },
  {
    idCelular: "CEL_0058",
    marca: "LG",
    modelo: "V60 ThinQ 5G",
    precio: "$799",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/NKDMPnP/image.png",
  },
  {
    idCelular: "CEL_0059",
    marca: "LG",
    modelo: "Wing",
    precio: "$999",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/VwD2Fwk/image.png",
  },
  {
    idCelular: "CEL_0060",
    marca: "Motorola",
    modelo: "Edge 20 Pro",
    precio: "$699",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/nn4LQqS/image.png",
  },
  {
    idCelular: "CEL_0061",
    marca: "Motorola",
    modelo: "Edge+",
    precio: "$999",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/VvBbh0C/image.png",
  },
  {
    idCelular: "CEL_0063",
    marca: "Motorola",
    modelo: "Moto G7 Plus",
    precio: "$329",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/c8bMzth/image.png",
  },
  {
    idCelular: "CEL_0064",
    marca: "Motorola",
    modelo: "Moto G9 Power",
    precio: "$229",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/XxtsL9M/image.png",
  },
  {
    idCelular: "CEL_0066",
    marca: "Motorola",
    modelo: "One Zoom",
    precio: "$449",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/frYykfk/image.png",
  },
  {
    idCelular: "CEL_0067",
    marca: "Motorola",
    modelo: "Razr",
    precio: "$1499",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/tM6p01w/image.png",
  },
  {
    idCelular: "CEL_0072",
    marca: "Samsung",
    modelo: "Galaxy A12",
    precio: "$179",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/CsgJVGH/image.png",
  },
  {
    idCelular: "CEL_0073",
    marca: "Samsung",
    modelo: "Galaxy A22 5G",
    precio: "$259",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/DtmBrzf/image.png",
  },
  {
    idCelular: "CEL_0074",
    marca: "Samsung",
    modelo: "Galaxy A50",
    precio: "$349",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/HnLjtpz/image.png",
  },
  {
    idCelular: "CEL_0075",
    marca: "Samsung",
    modelo: "Galaxy A51 5G",
    precio: "$499",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/1Myj445/image.png",
  },
  {
    idCelular: "CEL_0076",
    marca: "Samsung",
    modelo: "Galaxy A52 5G",
    precio: "$499",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/VTnXF8Y/image.png",
  },
  {
    idCelular: "CEL_0077",
    marca: "Samsung",
    modelo: "Galaxy A71",
    precio: "$479",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/HHHtC6m/image.png",
  },
  {
    idCelular: "CEL_0078",
    marca: "Samsung",
    modelo: "Galaxy A71 5G",
    precio: "$599",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/HHHtC6m/image.png",
  },
  {
    idCelular: "CEL_0079",
    marca: "Samsung",
    modelo: "Galaxy A72",
    precio: "$449",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/7QRMH2W/image.png",
  },
  {
    idCelular: "CEL_0080",
    marca: "Samsung",
    modelo: "Galaxy A9",
    precio: "$599",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/pryBKpB/image.png",
  },
  {
    idCelular: "CEL_0081",
    marca: "Samsung",
    modelo: "Galaxy M51",
    precio: "$399",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/yRTkBbp/image.png",
  },
  {
    idCelular: "CEL_0083",
    marca: "Samsung",
    modelo: "Galaxy Note 10+ 5G (Exynos)",
    precio: "$1199",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/YP0FF3J/image.png",
  },
  {
    idCelular: "CEL_0085",
    marca: "Samsung",
    modelo: "Galaxy Note 9",
    precio: "$1009",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/NWXwfFH/image.png",
  },
  {
    idCelular: "CEL_0086",
    marca: "Samsung",
    modelo: "Galaxy Note20 (Exynos)",
    precio: "$959",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/kcJ2r0P/image.png",
  },
  {
    idCelular: "CEL_0088",
    marca: "Samsung",
    modelo: "Galaxy Note20 Ultra 5G (Exynos)",
    precio: "$1309",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/GPKq5QW/image.png",
  },
  {
    idCelular: "CEL_0090",
    marca: "Samsung",
    modelo: "Galaxy S10 5G (Exynos)",
    precio: "$1199",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/Kh0skGr/image.png",
  },
  {
    idCelular: "CEL_0092",
    marca: "Samsung",
    modelo: "Galaxy S20 FE (Exynos)",
    precio: "$659",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/SJCnnxK/image.png",
  },
  {
    idCelular: "CEL_0093",
    marca: "Samsung",
    modelo: "Galaxy S20 Ultra 5G (Exynos)",
    precio: "$1359",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/FHfb7b5/image.png",
  },
  {
    idCelular: "CEL_0094",
    marca: "Samsung",
    modelo: "Galaxy S20+ (Exynos)",
    precio: "$1009",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/S0Qcj9J/image.png",
  },
  {
    idCelular: "CEL_0095",
    marca: "Samsung",
    modelo: "Galaxy S21 5G (Exynos)",
    precio: "$859",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/PTxqhzZ/image.png",
  },
  {
    idCelular: "CEL_0098",
    marca: "Samsung",
    modelo: "Galaxy S21 Ultra 5G (Exynos)",
    precio: "$1259",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/M2x7McY/image.png",
  },
  {
    idCelular: "CEL_0100",
    marca: "Samsung",
    modelo: "Galaxy S21+ 5G (Exynos)",
    precio: "$1059",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/6ZdVjS0/image.png",
  },
  {
    idCelular: "CEL_0106",
    marca: "Samsung",
    modelo: "Galaxy S9+",
    precio: "$959",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/wgkH8Zg/image.png",
  },
  {
    idCelular: "CEL_0107",
    marca: "Samsung",
    modelo: "Galaxy Z Flip",
    precio: "$1380",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/d7WgfBg/image.png",
  },
  {
    idCelular: "CEL_0108",
    marca: "Samsung",
    modelo: "Galaxy Z Fold2 5G",
    precio: "$1999",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/4gRnJ56/image.png",
  },
  {
    idCelular: "CEL_0109",
    marca: "Samsung",
    modelo: "Galaxy Z Fold3 5G",
    precio: "$1799",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/NW41CC1/image.png",
  },
  {
    idCelular: "CEL_0110",
    marca: "Sony",
    modelo: "Xperia 1",
    precio: "$999",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/QNFWnm8/image.png",
  },
  {
    idCelular: "CEL_0111",
    marca: "Sony",
    modelo: "Xperia 1 II",
    precio: "$1199",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/JcNJd80/image.png",
  },
  {
    idCelular: "CEL_0112",
    marca: "Sony",
    modelo: "Xperia 1 III",
    precio: "$1299",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/DVDbJRn/image.png",
  },
  {
    idCelular: "CEL_0113",
    marca: "Sony",
    modelo: "Xperia 5",
    precio: "$799",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/3YYcvFh/image.png",
  },
  {
    idCelular: "CEL_0114",
    marca: "Sony",
    modelo: "Xperia 5 II",
    precio: "$949",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/RbYPy90/image.png",
  },
  {
    idCelular: "CEL_0126",
    marca: "Xiaomi",
    modelo: "11T",
    precio: "$499",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/yRkBz6K/image.png",
  },
  {
    idCelular: "CEL_0127",
    marca: "Xiaomi",
    modelo: "11T Pro",
    precio: "$699",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/BsTMnV3/image.png",
  },
  {
    idCelular: "CEL_0128",
    marca: "Xiaomi",
    modelo: "Mi 10 Pro",
    precio: "$999",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/4SLwqFP/image.png",
  },
  {
    idCelular: "CEL_0129",
    marca: "Xiaomi",
    modelo: "Mi 10 Ultra",
    precio: "$803",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/YWLKzXW/image.png",
  },
  {
    idCelular: "CEL_0130",
    marca: "Xiaomi",
    modelo: "Mi 10S",
    precio: "$499",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/QQsDM6K/image.png",
  },
  {
    idCelular: "CEL_0131",
    marca: "Xiaomi",
    modelo: "Mi 10T 5G",
    precio: "$499",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/0BYGbsW/image.png",
  },
  {
    idCelular: "CEL_0132",
    marca: "Xiaomi",
    modelo: "Mi 10T Pro 5G",
    precio: "$599",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/BVNN5P6/image.png",
  },
  {
    idCelular: "CEL_0133",
    marca: "Xiaomi",
    modelo: "Mi 11",
    precio: "$799",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/F4PFW1Z/image.png",
  },
  {
    idCelular: "CEL_0134",
    marca: "Xiaomi",
    modelo: "Mi 11 Lite 5G",
    precio: "$399",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/JBhmfY0/image.png",
  },
  {
    idCelular: "CEL_0135",
    marca: "Xiaomi",
    modelo: "Mi 11 Ultra",
    precio: "$1200",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/QKWPJv5/image.png",
  },
  {
    idCelular: "CEL_0136",
    marca: "Xiaomi",
    modelo: "Mi 11i",
    precio: "$699",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/LvgdTPf/image.png",
  },
  {
    idCelular: "CEL_0137",
    marca: "Xiaomi",
    modelo: "Mi 8",
    precio: "$499",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/8mdR8TX/image.png",
  },
  {
    idCelular: "CEL_0138",
    marca: "Xiaomi",
    modelo: "Mi 9",
    precio: "$469",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/vPVL53j/image.png",
  },
  {
    idCelular: "CEL_0139",
    marca: "Xiaomi",
    modelo: "Mi CC9 Pro Premium Edition",
    precio: "$530",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/37cqMz1/image.png",
  },
  {
    idCelular: "CEL_0140",
    marca: "Xiaomi",
    modelo: "Mi MIX 3",
    precio: "$599",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/sKRqhS8/image.png",
  },
  {
    idCelular: "CEL_0142",
    marca: "Xiaomi",
    modelo: "Pocophone F1",
    precio: "$329",
    lanzamiento: 2018,
    imagen: "https://i.ibb.co/gtSYMV9/image.png",
  },
  {
    idCelular: "CEL_0143",
    marca: "Xiaomi",
    modelo: "Redmi 9",
    precio: "$159",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/qMdSqCy/image.png",
  },
  {
    idCelular: "CEL_0144",
    marca: "Xiaomi",
    modelo: "Redmi K20 Pro",
    precio: "$379",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/n3BQf6G/image.png",
  },
  {
    idCelular: "CEL_0145",
    marca: "Xiaomi",
    modelo: "Redmi K30 Pro Zoom Edition",
    precio: "$575",
    lanzamiento: 2020,
    imagen: "https://i.ibb.co/2dN1SD4/image.png",
  },
  {
    idCelular: "CEL_0146",
    marca: "Xiaomi",
    modelo: "Redmi K40 Gaming",
    precio: "$303",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/pjPR6X0/image.png",
  },
  {
    idCelular: "CEL_0147",
    marca: "Xiaomi",
    modelo: "Redmi K40 Pro+",
    precio: "$560",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/kJJhVwz/image.png",
  },
  {
    idCelular: "CEL_0148",
    marca: "Xiaomi",
    modelo: "Redmi Note 10",
    precio: "$199",
    lanzamiento: 2021,
    imagen:
      "https://i.ibb.co/PNxrwVP/D-NQ-NP-758267-MLA53286844819-012023-O.webp",
  },
  {
    idCelular: "CEL_0149",
    marca: "Xiaomi",
    modelo: "Redmi Note 10 5G",
    precio: "$229",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/W5HMb6R/image.png",
  },
  {
    idCelular: "CEL_0150",
    marca: "Xiaomi",
    modelo: "Redmi Note 10 Pro",
    precio: "$279",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/YRdsY2y/image.png",
  },
  {
    idCelular: "CEL_0151",
    marca: "Xiaomi",
    modelo: "Redmi Note 10S",
    precio: "$199",
    lanzamiento: 2021,
    imagen: "https://i.ibb.co/SrN5S6G/image.png",
  },
  {
    idCelular: "CEL_0152",
    marca: "Xiaomi",
    modelo: "Redmi Note 8 Pro",
    precio: "$249",
    lanzamiento: 2019,
    imagen: "https://i.ibb.co/LkR67w9/image.png",
  },
];
